export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_BEGIN = 'FETCH_ORDERS_BEGIN';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCH_SINGLE_ORDER = 'FETCH_SINGLE_ORDER';
export const POST_REGISTER = 'POST_REGISTER';
