//Orders
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_RECEIVE = 'FETCH_ORDERS_RECEIVE';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
//NavigationCategory
export const FETCH_CATEGORIES_FOR_NAVIGATION = 'FETCH_CATEGORIES_FOR_NAVIGATION';
//Products
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_RECEIVE = 'FETCH_PRODUCTS_RECEIVE';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
//ProductsCategory
export const FETCH_PRODUCTS_IN_CATEGORY_REQUEST = 'FETCH_PRODUCTS_IN_CATEGORY_REQUEST';
export const FETCH_PRODUCTS_IN_CATEGORY_RECEIVE = 'FETCH_PRODUCTS_IN_CATEGORY_RECEIVE';
export const FETCH_PRODUCTS_IN_CATEGORY_FAIL = 'FETCH_PRODUCTS_IN_CATEGORY_FAIL';
//Register
export const POST_REGISTER_BEGIN = 'POST_REGISTER_BEGIN';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAIL = 'POST_REGISTER_FAIL';
// Admin logIn
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_WRONG = 'ADMIN_LOGIN_WRONG';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
